// <auto-generated />
using System;
using MailBookApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MailBookApi.Migrations
{
    [DbContext(typeof(MailBookDbContext))]
    partial class MailBookDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MailBookApi.Data.Entities.DeliverCompanyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DeliverCompanies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "DHL"
                        },
                        new
                        {
                            Id = 2,
                            Name = "SCG"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Flash"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Kerry"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Lex"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Shoppee"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Lazada"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Thai Post"
                        });
                });

            modelBuilder.Entity("MailBookApi.Data.Entities.PackageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ArrivedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeliverCompanyId")
                        .HasColumnType("int");

                    b.Property<string>("PackageNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("DeliverCompanyId", "PackageNumber")
                        .IsUnique();

                    b.ToTable("Packages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArrivedDate = new DateTime(2021, 10, 15, 12, 0, 1, 0, DateTimeKind.Unspecified),
                            DeliverCompanyId = 2,
                            PackageNumber = "PKG000001"
                        });
                });

            modelBuilder.Entity("MailBookApi.Data.Entities.PackageEntity", b =>
                {
                    b.HasOne("MailBookApi.Data.Entities.DeliverCompanyEntity", "DeliverCompany")
                        .WithMany()
                        .HasForeignKey("DeliverCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeliverCompany");
                });
#pragma warning restore 612, 618
        }
    }
}
