GET https://localhost:5001/api/deliver-company HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJBcmFoayIsImF1ZCI6Im1haWxib29rLm5laWdoYm9yb3MuaW4udGgiLCJzdWIiOiJBcmFoayIsImlzcyI6Imh0dHBzOi8vYXV0aC5uZWlnaGJvcm9zLmluLnRoIiwiZW1haWwiOiJhcmFoa0BvdXRsb29rLmNvbSIsIm5iZiI6MTYzNzY4MzIwOSwiZXhwIjoxNjM3NjgzODA5LCJpYXQiOjE2Mzc2ODMyMDl9.3EDBhkBEhLiVgG5QM5PUlmBNWe_7KxcoybSWrWc6AEI