FROM mcr.microsoft.com/dotnet/sdk:5.0 AS BUILD
WORKDIR /source/MailBookAPI

COPY ./MailBookApi .
RUN dotnet publish -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS Runtime
WORKDIR /app
COPY --from=BUILD /app .

ENV ASPNETCORE_ENVIRONMENT=Release

ENTRYPOINT [ "dotnet", "MailBookApi.dll", "--ef-migrate" ]