name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./MailBookApi
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./MailBookApi
    - name: Test
      run: dotnet test
      working-directory: ./MailBookApi.Test
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build Docker Image and Push
      uses: docker/build-push-action@v2
      with:
        context: ./MailBookApi
        push: true
        tags: arahk/neighbor-os-mailbook-api:latest
